/** App wide head for app wide metadata  */
export default function Head() {
  return (
    <>
      <title>Excel Simplify</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* Need to add google_signin_client_id firebase? */}
      <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com"></meta>
      <link rel="icon" href="/favicon.ico" />
      <script src="https://apis.google.com/js/platform.js" async defer></script>
    </>
  );
}
